name: greatly_user
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.6.2


dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_messaging: ^15.2.4
  dio: ^5.8.0+1
  get_it: ^8.0.3
  injectable: ^2.5.0
  flutter_bloc: ^9.1.0
  shared_preferences: ^2.5.2
  flutter_secure_storage: ^9.2.4
  intl: ^0.20.2
  flutter_animate: ^4.5.2
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^6.1.4
  equatable: ^2.0.7
  google_fonts: ^6.2.1
  dartz: ^0.10.1
  http: ^1.3.0
  freezed: ^2.5.7
  internet_connection_checker: ^1.0.0+1
  cached_network_image: ^3.3.0
  logger: ^2.0.1
  shimmer: ^3.0.0
  json_annotation: ^4.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_stripe: ^9.0.0
  url_launcher: ^6.3.1
  webview_flutter: ^4.13.0
  webview_flutter_android: ^4.7.0
  webview_flutter_wkwebview: ^3.22.0
  flutter_local_notifications: ^19.2.1
  googleapis_auth: ^2.0.0
  image_picker: ^1.1.2
  delightful_toast: ^1.1.0
  flutter_launcher_icons: ^0.14.4
  
dev_dependencies:
  flutter_test:  
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  

  
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/


  # Flutter Launcher Icons configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/greatness.png"
