// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_GwAaPjfIwBn4flRwGmFgZIhOdWK0aXQ',
    appId: '1:236301618251:web:33acac694124e079cf11ce',
    messagingSenderId: '236301618251',
    projectId: 'greatlyshopapp-f0b87',
    authDomain: 'greatlyshopapp-f0b87.firebaseapp.com',
    storageBucket: 'greatlyshopapp-f0b87.firebasestorage.app',
    measurementId: 'G-FR0ZDM30YJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6F0x_3_Xxqa4vHPsu1010PTfcpPhR0rw',
    appId: '1:236301618251:android:552de583971065c6cf11ce',
    messagingSenderId: '236301618251',
    projectId: 'greatlyshopapp-f0b87',
    storageBucket: 'greatlyshopapp-f0b87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQuxvMlAkypr1pJAtkAzJyq1YqZjN_hL4',
    appId: '1:236301618251:ios:d3dbf85bf6950cd2cf11ce',
    messagingSenderId: '236301618251',
    projectId: 'greatlyshopapp-f0b87',
    storageBucket: 'greatlyshopapp-f0b87.firebasestorage.app',
    iosBundleId: 'com.example.greatlyUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQuxvMlAkypr1pJAtkAzJyq1YqZjN_hL4',
    appId: '1:236301618251:ios:d3dbf85bf6950cd2cf11ce',
    messagingSenderId: '236301618251',
    projectId: 'greatlyshopapp-f0b87',
    storageBucket: 'greatlyshopapp-f0b87.firebasestorage.app',
    iosBundleId: 'com.example.greatlyUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_GwAaPjfIwBn4flRwGmFgZIhOdWK0aXQ',
    appId: '1:236301618251:web:996bfc7a51598375cf11ce',
    messagingSenderId: '236301618251',
    projectId: 'greatlyshopapp-f0b87',
    authDomain: 'greatlyshopapp-f0b87.firebaseapp.com',
    storageBucket: 'greatlyshopapp-f0b87.firebasestorage.app',
    measurementId: 'G-SGVRCMYS07',
  );
}
